### ISSUE TITLE
book browse list fields

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#14]
As a data editor, when I’m browsing the list of books I want to see the author, short title, publication year, owning institution call number, and whether a book is extant, annotated, and/or digitized so that I can get a quick overview of volumes.

**Comment by jmrampling** [comment]
Books appear to have been listed by the order in which they've been added to the system, which is unlikely to be meaningful for most users. Could we have the option of arranging the browse list in different ways: e.g. alphabetically by title (excluding "the" and "a"), alphabetically by author surname, and chronologically by date of publication?

**Comment by rlskoeser** [comment]
@jmrampling great catch, I didn't set a default sort!  Is title a reasonable default for sorting?

Several of the headings in the django admin list view can be clicked for sorting purposes, see attached screenshot.
<img width="1663" alt="screen shot 2017-01-26 at 3 51 19 pm" src="https://cloud.githubusercontent.com/assets/691231/22349894/a578c6b0-e3df-11e6-9073-d0cf1f141b74.png">

Alpha by author doesn't work in the Django admin because of the way the data is structured, and I\ think alpha by sort title should probably be out of scope for this phase (but definitely worth thinking about for the public search interface!).

**Comment by rlskoeser** [comment]
Well, it's sorting by title but only displaying short title - and I can see that they don't match up, so that might be confusing.  Let me know what you want in terms of default sort and which title(s) should be in the browse list.

**Comment by christianflow** [comment]
I think it's going to be fine to default sort by short title (which are the displayed titles), especially since if there are problems one has the option to search for a word in the full title to bring up the corresponding short title. What this means is that we are going to have to do a great deal more work to clean up our short-titles, which are now somewhat haphazardly arrayed in our spreadsheet (and often not included at all). Would it be possible to make it possible to click/sort by Authors as well (as you can, e.g., by publication year currently when browsing the list of books).

**Comment by bwhicks** [comment]
I'm going to reopen this one since there was a request for a tweak to functionality.

Also, on the data import, if there is no short title, the import script will build one out of the first three words of a title. It's not ideal but it does mean that you'll have something to work with and not a blank space.

**Comment by bwhicks** [comment]
This should now be an option for author on the book display list.

**Comment by christianflow** [comment]
Ben, This looks perfect for "author" on the book display list. Very convenient to be able to sort that way. I think it was a great idea on the data import to have the script manufacture a makeshift short-title. Now that I see the convenience of the short titles for the purpose of display on the site (the long ones are too unwieldy to really work with) it's clear that we're going to want to give solid ones for all the texts. I'll try to do that in the spreadsheet sometime soon (probably over the weekend).
