### ISSUE TITLE
book browse list filters

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#15]
As a data editor, when I’m browsing the list of books I want to filter by subject or language or whether extant, annotated, digitized, so that I can quickly look at a particular subset of books.

**Comment by mcmcmahon** [comment]
Subject--works fine, Alchemy brings up "The Wizard of Oz" by Jenny RAmpling...
Langauge -- Ancient Greek brings up Wizard of Oz and Historia Ecclesiastica (though that's because my edits to remove all language for Historia Ecclesiastica (Win 132) were unsuccessful. But the filtering works fine!
Extant--yes, works great.
Annotated or not--works.
Digitized or not--yes, works.

Multiple filters at once also work (langauge and digitized, e.g.).
