### ISSUE TITLE
add/edit people

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#17]
As a data editor, I want to add a new or edit an existing person so that I can document people associated with the Winthrop Family and their books.

**Comment by christianflow** [comment]
Noted one potential problem with this: I changed somebody's information so that they had a Residence and a "From Relationship." When I then looked to change it so that once again no residence and no from relationship would be listed it informed me that fields "Place" (under Residence) and fields "Relationship" and "to person" (under From Relationships) were required. It needs to be easy to change the information so that for any of these fields nothing is there (often we will not have a Residence or will have been mistaken about a From Relationship and want to simply remove it).

**Comment by christianflow** [comment]
This looks great.

**Comment by bwhicks** [comment]
The comment looks to have vanished on this one. I suspect it may be a Grappelli interface issue such that you remove inlines (like Residence or From Relationship) by clicking the 'X' to toggle the inline red and then hit 'save' to make those changes.
