### ISSUE TITLE
add/edit footnote and associate with anything

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#28]
As a data editor, I want to add a new or edit an existing footnote and associate it with any other kind of record in the system so that I can document evidence related to assertions made elsewhere in the data.

**Comment by christianflow** [comment]
Not sure we're quite there on this yet. We can add/edit footnote inline when editing book information and insert into the "note" what it has to do with the content there. But the same option does not exist, e.g., for "People" editing. So to associate a footnote documenting a particular person-person or interaction with the person involved does not yet seem to be a possibility. Could go inline with the person-edit the same as currently happens with the book-edit. Also worth asking whether there is an easy way to associate footnote with precisely the information that it serves to document (i.e., whether we are using it to support Person-Book interaction or Person-Person relationship). I also wonder whether this will not all prove to be superfluous since we have space to add "notes" for almost every field as it is: perhaps instead of the "notes field" in each case there should be a footnote form.

**Comment by christianflow** [comment]
I think the last option would be the ideal: right now for instance we have a "Notes" field next to each Person-Book interaction slot. Best would be if we just tweaked that so that IN ADDITION to a blank "Notes" field you had the option to add a new, more formal "Footnote" (via a PLUS sign link) there (and, e.g., in any other place, including in "Person" editing, where a "Notes" field occurs). In sum: use same  Footnote form as we now have, but instead of having Footnotes simply segregated by themselves at the bottom of the "Books" form, allow people to add "Footnotes" in addition to "Notes" wherever there are now "Notes" fields.

**Comment by bwhicks** [comment]
At the very least, I can easily add footnote as an inline to person and have done so on the develop code branch.

This other functionality I'll need to work on, because it may not be possible in the current set up, at least directly. Django admin doesn't let you inline inlines (and that's the only real existence footnotes have as the current model stands).

I'll have more on this and the other issue this afternoon.

**Comment by bwhicks** [comment]
Having discussed this with @jabauer, I've added this as stated to person as a model. We can't easily add this as an inline, so my instinct is to have you double-check footnote on person (which should now appear once I push this to dev), and hold off on adding it to other models for a later milestone.

We can always add the model back to admin and include footnote, if that relationship needs them frequently enough.

**Comment by rlskoeser** [comment]
@christianflow @bwhicks there is another way to add footnotes and associate it with anything, but I don't think I ever documented it!  My apologies. 

In the admin interface, in the footnotes section, you can add a footnote directly and associate it with pretty much anything else in the database.  You have to pick a *content type* and then you can do a lookup to find the id for that content type (clicking the search icon brings up a version of the admin browse list).  However, it does look like the lookup is currently broken for some content types, so we'll need to revisit that.  

The inline footnotes were just added as a convenience on the models where we thought you would be most likely to be adding footnotes.

**Comment by rlskoeser** [comment]
Moving this story to annotation admin milestone so it doesn't get lost.

**Comment by christianflow** [comment]
This isn't quite intuitive yet: tried to add a footnote from the Footnote part of the Admin interface and found that "Object ID" is just a list of numbers, so it's hard to peg what/whom I'm footnoting.

**Comment by rlskoeser** [comment]
@christianflow this was broken because of the javascript issue you identified (#59).  Once you've selected a content type, you should see a search button next to the object id input. Clicking on that 
will open a window where you can select items from the same list you'd see elsewhere in the admin interface.  You should *not* have to enter items by numeric id.

![screen shot 2017-06-12 at 4 56 39 pm](https://user-images.githubusercontent.com/691231/27054833-645331ee-4f90-11e7-9f45-70b21a37454c.png)

It may never be super intuitive, but hopefully it is workable enough for what we need, and something you can document and train people on if necessary.

**Comment by christianflow** [comment]
This is working great now. The only thing I would say -- and I have a feeling that there's not going to be the time to change this -- is that we could be a little better about where the footnote shows up. So for instance (I'm using my test scenario): say I know that Abelin is a borrower of a particular book bc I read it somewhere else. So I want to footnote that person/book interaction with the page and snippet from the secondary work or letter that alerts me to the interaction. This is a very good thing, allows me to store good information. The less-than-optimal thing on the back-end (this could probably be rectified on the front end) is that the footnote than only shows when I click into person/book interactions and look at Abelin as borrower. Whereas it might be helpful to have it show up also when I click in under Abelin (in PEOPLE) since there, too, his relationship to the book is logged/reflected. And also when I click into the BOOK with which he has a relationship (if the relationship is going to be recorded there, one would want it also to be marked as having been documented by a FN if possible).

**Comment by rlskoeser** [comment]
@christianflow you're right in terms of timing, we need to finish this release and get it out so you all can start using it.  Now that this is working, please go ahead and accept it and then we can think improving the interface later on.

This is good feedback, though.  I've asked @xinyil to think some about where footnotes should show up on the front end (I think they're not really accounted for in the current design?), and it would be great to have the project team thinking about it too.  Once this feature is live in production and you start entering the footnotes, we'll be able to look at some specific examples and think more concretely about where and how footnotes should be made visible.

For now, why don't you create a new issue and draft a user story based on your suggestions here for where you'd like to see footnotes displayed in the admin interface?  Then we won't forget about it, and we'll be able to look at adding that feature in an upcoming release and prioritize it against the other work that needs to be done.
