### ISSUE TITLE
add/edit languages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#4]
As a data editor, I want to add a new or edit an existing language so that I can document the languages used in books in a standard way.

**Comment by mcmcmahon** [comment]
First I took the Historia Ecclesiastica (1600) and added 3 languages: Greek, Dutch, English. That all worked and saved. But then I made the book only in Algonquin (a language I added) and it would not let me save because then the 2nd and 3rd labels (because I had entered 2 other languages prior I think?). So that's another issue to be noted. Thanks.

**Comment by rlskoeser** [comment]
@mcmcmahon I'm not sure I understand the problem exactly.  Did you use the red X at the far right to remove the languages you no longer wanted associated with the book?

<img width="1652" alt="screen shot 2017-01-26 at 2 40 22 pm" src="https://cloud.githubusercontent.com/assets/691231/22347281/6757276e-e3d5-11e6-8fff-ef651ee01738.png">

**Comment by mcmcmahon** [comment]
Dear Rebecca,

Ah, I see! The browser window I had open at the time wasn't large enough for me to see the red X (or I just didn't see it) and I couldn't figure out how to remove. That makes perfect sense, thanks.
