### ISSUE TITLE
annotation tags

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#43]
As an annotation data editor, I want the option of associating tags with an annotation so that I can categorize marginalia consisting of visual elements.

(Example tags from use case: manicule, dash, underlining, probatio pennae, monad, alchemical symbol, cipher)

**Comment by rlskoeser** [comment]
I've already turned on the default annotator tag plugin.  The story doesn't explicitly say anything about a controlled list or auto-complete, so we might be fine to leave as is.    With this approach, it might be a good idea to create a model field for tags (text-based list field, perhaps?) so that they are easier to manage and edit, rather than where they currently are in the `jsonfield` extra data.

If we do need more control on the tags, we'll have to create a simple tag model somewhere (perhaps in `winthrop.annotations`), add an autocomplete view, and bind a multi-value autocomplete lookup to the tag field.  It might be a bit tricky to support adding new tags to the database dynamically by simply using them on an annotation, but should be possible (either via the view or create when an annotation is saved).

**Comment by christianflow** [comment]
I will add another user story, because I think it would be good if we did autocomplete for the tags and ensured that they came from a fixed list (to which tags could be added or deleted as needed). Otherwise, I fear people would be too easily inclined to duplicate the same tag in non-standard ways. The process for adding tags and associating them would be similar to the functionality we have for associating books with subjects (and for adding or deleting subjects).

**Comment by christianflow** [comment]
Works like a charm.
