### ISSUE TITLE
annotation + subject

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#44]
As an annotation data editor, I want the option of associating annotations with any of the subjects in the database that are used for labeling books.

**Comment by christianflow** [comment]
Not sure this is working quite right yet. What we want is for this to be available in the portion where you are adding Annotation Text / Annotation Language/ Author / Annotation Translation / etc. So right under the section that reads "Add tags here separated by commas" we want to add another field that allows "Add SUBJECT tags here separated by commas." The former tags are for non-visual elements, the latter tags are for the subject (auto-complete list from the already extant list of book subjects) that the annotation treats.

**Comment by bwhicks** [comment]
Reopening this issue with approval pending making the change above (I take it that Christian trusted us to duplicate functionality).

**Comment by bwhicks** [comment]
Adding a note on this to document that the team will want the autocomplete (and the people list) to involve people who have person-book associations (which should grab the Winthrops?),
@rlskoeser, tagging you to make sure we've both been understanding this correctly.

**Comment by bwhicks** [comment]
@christianflow Question re: functionality -- 1) are there use cases where a single annotation willhave more than one subject tag? 2) If yes, does the team need to be able to designate one that is primary?

**Comment by christianflow** [comment]
Hey Ben, Yes I think it'll frequently be the case that a single annotation will have multiple subject tags, so that capacity we surely want to have. It's conceivable that three, four subjects might apply to the same annotation. In principle a "primary tag" feature could potentially be useful, but it seems like it would be more work than it's worth at this point. This is the type of thing where down the road we'll understand better whether there's an inefficiency (i.e., sorting yields a lot of tagged items that are really only peripheral to the chosen subject). For right now, I think we're fine with just being able to designate multiple subjects.

**Comment by christianflow** [comment]
Looks good.
