### ISSUE TITLE
annotation author

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#47]
As an annotation data editor, I want to associate an annotation with the person who wrote it so that I can document the author when that information is known.

**Comment by christianflow** [comment]
This works, but I was thinking: right now the "People" that we have listed in the site are the 280-odd authors of the different books in the database. I think it might behoove us to not make it so that an author of a book defaults into the People section, though the option to put an "author" into the People section should exist. I say this simply because it is very rare that the People whose information we are using the site to track in an elaborated way (i.e., by listing them as an Annotator, or as a Purchaser of a Book, or as an Owner of a given book) are going to be authors of books. They tend to be Winthrops and their associates (probably a group of only ten or so at this point). It is this smaller group that we would want to fall under "People." The reason is simply one of streamlining: e.g., when I'm entering an Annotator in the Annotations database, I get an autocomplete list from "People" that is really long: when really that autocomplete list needn't be very long at all, which makes my navigation easier. Not a necessity, but an idea.

**Comment by bwhicks** [comment]
Reopening this one to address the desire to prioritize Winthrops and associates in the listing

**Comment by bwhicks** [comment]
This functionality now exists on the test server. I created two obviously fake Winthrops to verify it (Another Winthrop and Forgotten Winthrop). Anyone who's a Winthrop is pulled up to the top. 

@christianflow This could be extended to be more complicated, but if most of the Winthrops and associates, are going to have the name Winthrop in their name, I assume this will grab the bulk of the issue.

You can still associate anyone else on the off chance that comes up, too. But Winthrops get first listing.

**Comment by rlskoeser** [comment]
@bwhicks @christianflow another thought on how to identify and privilege Winthrops for this feature - would it make sense to use the family group field?  That is, any person with a family group set would be prioritized as more likely to be an annotator.

**Comment by bwhicks** [comment]
The commit I pushed (but haven't sent to test yet), implements a search via anyone who has a person book relationship, which should always favor Winthrop when they're added, as well as their associates.

**Comment by rlskoeser** [comment]
@bwhicks I was looking at Christian's notes again and wanted to check - do we want to *restrict* to people associated with books, or just prioritize them so they sort to the top?  I ask because I noticed this in Christian's comment above:
> ... though the option to put an "author" into the People section should exist

I think your current implementation doesn't allow this.

It also occurred to me that it might also make sense to prioritize people who've already been entered as an annotator.  I.e., once you associate a person with an annotation, even if you haven't yet entered any person/book associations, they would be prioritized in the list.

FWIW, if this is getting too complicated we can decide we need to postpone this enhancement so that we can get the release out sooner.

**Comment by bwhicks** [comment]
@rlskoeser This is where my confusion during the meeting was coming from. The comments imply that other authors should be an option, and I originally had it simply sorting them to the top using annotate+order_by.

Then during the meeting, I took it that it should only be Winthrops and associates in practical terms on further clarification (hence the simpler filter). I'll mark this issue with a question for @christianflow if that's amenable.

I like the idea of prioritizing people who are associated with an annotation.

**Comment by bwhicks** [comment]
@christianflow, @rlskoeser and met and wanted to run this by you. Two questions for the annotation author autocomplete:

1) Does the team want the annotation author to only be Winthrops and associates **OR** Winthrops prioritized + all other people in the database listed thereafter?  
2) Is there a way that would be best to identify Winthrops and associates? The dev team has discussed prioritizing any people with a family group set and anyone who has already been set as an annotation author.

Let us know and we'll proceed from there. Thanks!

**Comment by christianflow** [comment]
Hi guys, Thanks for the work on this, and sorry for the confusion. I think the easiest way to deal with this, if possible, would probably be to make it possible to tag people as annotators. That is to say, if a particular author is an annotator, I would toggle a switch in the People-Information section that identifies him/her as an annotator: he/she would then show up in the Autocomplete for the annotation section. Likewise, if I was to encounter a book annotated by a person not yet entered into the site (e.g., Samuel Lee), I would create a new person, add the birth-death date and the people-book relations, and toggle an "Annotator" switch so that they would show up in the Annotation complete. There might be a more elegant way to do this according to the People-People and People-Book interactions functionality that we already have: i.e., a People-Book interaction would be "Annotator" and anyone for whom such an interaction is designated would show up in the Autocomplete. There is no need for other people (e..g. the vast majority of the authors of the books) to show up in the Autocomplete there: they weren't annotators. Hope this helps! More soon, Christian

**Comment by bwhicks** [comment]
@christianflow For testing on this one, please create a person-book relationship with one or more people in the database. They should then appear on the autocomplete for annotations.

**Comment by christianflow** [comment]
Having problems with this, because I'm not able to smoothly create a person-book relationship. I think first of all we want to make it possible to do person-book relationships directly from "Person" interface: right now it is only possible thoruhg the "Books" interface. Second, in the books interface (and this is the case also in the "People" interface) I can't create the Person-Book interaction (or in the later case, the Person-Person interaction) because there is no autocomplete for "Person." I can't activate anybody in the necessary field. So we need to get those things ironed out before we test this. "Annotator" should be added as a possible "person-book relationship" (as opposed e.g. to simply reader. We could have "reader" and "reader-annotator": the former for people who we know read things (but left no marks) the latter for those who left marks. The "reader-annotators" we would want to rise to the top in the autocomplete field as choices for "annotator" in the annotations module.

**Comment by rlskoeser** [comment]
@christianflow the autocomplete was broken because of the javascript issue #59 - sorry about that.

You have access to edit the person-book relationship types, so you can certainly add a new one for Annotator.  I would say, rather than creating a "reader-annotator" relationship, you add two person/book relationships when someone both read and annotated a book (or maybe reader is redundant if someone is an annotator?  would someone annotated without reading?).

At this point we need to get the release out and can't be adding new functionality.  We could consider adding person-book relationship editing from the Person edit interface as well as or instead of the Book edit page later on.  We could also look at fine-tuning the sorting of people in the annotation author autocomplete later on if the team discovers it would make a big difference.  For now unless the annotation author feature is unusable, I think we should consider it acceptable so we can get these new features into production.

**Comment by christianflow** [comment]
I tested this and I love it. Only people who are registered under BOOKS has having a PERSON-BOOK relationship show up to be entered as annotators in the annotation module. This reduces the clutter and helps us make sure we're strict about logging the person-book relationship when we know the identity of an annotator. Great stuff!
