### ISSUE TITLE
book counts on subject, language, publisher, owning institution

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#7]
As a data editor, when I’m browsing the list of subjects, languages, publishers, or owning institution, I want to see a count of the number of books associated with each subject, language, publisher, or owning institution so I can get a sense of the distribution of books.

**Comment by mcmcmahon** [comment]
re: subject - no books (except Jenny's Wizard of Oz, hah) have subjects but 19 subjects exist, and when I click on the subject to see the book(s) within the subject
re: language - this does work although we clearly need to do more work adding language to the spreadsheet, since only a handful of books have languages listed (also we can probably get rid of Algonquin-- I added that as a language and now can't figure out how to remove it, sorry!)
re: publishers -- a lot cleaning up on our end to do; but yet again like subject I can't get to a list of the books published by Publisher (eg Adam Islip)
re: owning institution-- same issue. I get the contact info etc when I click on NYSL but I don't get a list of the books, which would be nice.

**Comment by mcmcmahon** [comment]
(Just to clarify: I can see count but I cannot get a list from there--I don't know if that's an issue or not.)

**Comment by rlskoeser** [comment]
@mcmcmahon I don't think there's an easy way for me to give you access to the list of books from the other lists.  The best way to view books by one of these categories is to use the filter option on the top right when you are looking at the list of books, although I'm not sure all of these are currently available as filters.  If we need to add more filters, let us know, that's easy to do.

<img width="1662" alt="screen shot 2017-01-26 at 3 45 26 pm" src="https://cloud.githubusercontent.com/assets/691231/22349664/99054bf2-e3de-11e6-85e3-5e9281a585f9.png">

**Comment by christianflow** [comment]
I took another look at this and think the filter works well for the purposes Maddie was raising. I do agree with her that it would be nice also to be able to summon lists of books directly through these sub-lists (so, e.g., I would be in "Languages" and click on "Ancient Greek" to see a list of books in Ancient Greek (i.e., exactly the same thing that is possible by searching with the "Ancient Greek" filter in the Books menu). But it's certainly not necessary at this point if it looks hard to do.

**Comment by bwhicks** [comment]
Hi, this one was pretty straightforward. I've done the dev and hit on a solution that works with the current setup. The book count is now a link that will display a filtered list of books in the django admin (1:1 functionality with the filter for any model that has a book count).

**Comment by christianflow** [comment]
This worked like a charm for the book-counts by subject. Loving it. Also worked for languages; I think it's a really neat feature. We could probably also do it for Publishers (where we also have click-through counts): that is, just match it 1:1 with the filter. Only if it's easy, because no pressing scenario comes to mind where this would have to be used in place of the filter.
