### ISSUE TITLE
As a user, I want to see an indication of which books in the list are annotated so I can look at the annotations.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/winthrop-django#71]
## Notes for testing
Books that are annotated should have a little "annotated" button. Books that are not annotated should not.
*NOTE:* currently this is keying on the `is_annotated` field in the database, which indicates whether the physical volume has annotations; that could mean there will be books marked as annotated that don't (yet) have annotations documented in the database. We could switch to key on the presence of annotations in the database if that makes more sense.

**Comment by stone-julia** [comment]
Looking through a few pages of the book browse feature showed this feature is clearly working (and looks great!). 

To me, it makes sense to leave this marker as is, indicating books that have annotations rather than database entries, but if we want to display that information perhaps we could add something like an "is searchable" tag for books entered in the database?
